(global-set-key (kbd "C-c a")     'align)
(global-set-key (kbd "C-c M-a")   'align-regexp)
(global-set-key (kbd "C-h")       'backward-delete-char)
(global-set-key (kbd "C-c d")     'delete-indentation)
(global-set-key (kbd "C-c C-m d") 'describe-bindings)
(global-set-key (kbd "C-x d")     'mark-defun)
(global-set-key (kbd "C-x f")     'fill-paragraph)
(global-set-key (kbd "C-x M-f")   'fill-region)
(global-set-key (kbd "M-g")       'goto-line)
(global-set-key (kbd "C-S-i")     'indent-region)
(global-set-key (kbd "C-m")       'newline-and-indent)
(global-set-key (kbd "C-t")       'next-multiframe-window)
(global-set-key (kbd "M-<RET>")   'ns-toggle-fullscreen)
(global-set-key (kbd "C-S-t")     'previous-multiframe-window)
(global-set-key (kbd "C-M-r")     'replace-regexp)
(global-set-key (kbd "C-r")       'replace-string)
(global-set-key (kbd "C-x F")     'set-fill-column)
(global-set-key (kbd "C-/")       'undo)

(global-set-key (kbd "C-x C-b")   nil)
(global-set-key (kbd "C-x M-b")   'list-buffers)